# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
      ./disk-config.nix
    ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "virtio_pci"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # required for sops-nix to find the decryption key
  fileSystems."/home".neededForBoot = true;

  sops.secrets."truenas/password_multimedia_ro" = { };
  sops.secrets."truenas/password_immich" = { };
  sops.secrets."truenas/password_restic_home_server_backup" = { };

  fileSystems."/mnt/truenas_multimedia" = {
    device = "//10.0.10.4/multimedia";
    fsType = "cifs";
    options = [ "credentials=${config.sops.secrets."truenas/password_multimedia_ro".path}" "x-systemd.automount" "x-systemd.device-timeout=60" "uid=1000" "gid=1000" "ro" ];
  };
  fileSystems."/mnt/truenas_immich" = {
    device = "//10.0.10.4/immich_data";
    fsType = "cifs";
    options = [ "credentials=${config.sops.secrets."truenas/password_immich".path}" "x-systemd.automount" "x-systemd.device-timeout=60" "uid=1000" "gid=1000" "rw" ];
  };
  fileSystems."/mnt/truenas_restic_home_server" = {
    device = "//10.0.10.4/restic/home_server";
    fsType = "cifs";
    options = [ "credentials=${config.sops.secrets."truenas/password_restic_home_server_backup".path}" "x-systemd.automount" "x-systemd.device-timeout=60" "uid=1000" "gid=1000" "rw" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
