keys:
  - &CBPC-0123LMH age1r8yka6c2znyhxvcy72etkwe9fpvd3fppt0lpps24kesta2ytup5svteznn
  - &Home-Server-2025-NixOS age163w9at8f2j75nnp9khy3zu792064yjxcn9eepwz6sqxphp6qccnsaryu0n
  - &Dell22_LMH age19ely98xsayrtqxkyd2xuyyw9edvp2um5fmq8xdy9cnd9j5fryp4szqum8c
  - &hsarr age16xquxdya8q62x620y0pqvtyf7j7nj0vvsenrc3pemru4y5gkjysq9rgam9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *CBPC-0123LMH
      - *Home-Server-2025-NixOS
      - *Dell22_LMH
      - *hsarr