keys:
  - &CBPC-0123LMH age1r8yka6c2znyhxvcy72etkwe9fpvd3fppt0lpps24kesta2ytup5svteznn
  - &Home-Server-2025-NixOS age163w9at8f2j75nnp9khy3zu792064yjxcn9eepwz6sqxphp6qccnsaryu0n
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *CBPC-0123LMH
      - *Home-Server-2025-NixOS