# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ad2efdc8-8e8f-4394-8861-86ab727723c5";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks".device = "/dev/disk/by-uuid/f89b907c-beaa-4475-8336-937e891cfe49";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ad2efdc8-8e8f-4394-8861-86ab727723c5";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/nix/store" =
    { device = "/dev/disk/by-uuid/ad2efdc8-8e8f-4394-8861-86ab727723c5";
      fsType = "btrfs";
      options = [ "subvol=@nix_store" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ad2efdc8-8e8f-4394-8861-86ab727723c5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/ad2efdc8-8e8f-4394-8861-86ab727723c5";
      fsType = "btrfs";
      options = [ "subvol=@.snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E151-32CE";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
