{
  "labels": {
    "backend": "local",
    "platform": "linux/arm64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "image": "bash",
      "name": "Setup Attic",
      "secrets": [
        "attic_key"
      ]
    },
    # for now commented out, as this device is no longer needed actively
    #{
    #  "commands": [
    #    "nix build '.#nixosConfigurations.pi4b.config.system.build.toplevel' -o 'result-pi4b'"
    #  ],
    #  "image": "bash",
    #  "name": "Build pi4b"
    #},
    #{
    #  "commands": [
    #    "attic push lounge-rocks:nix-cache 'result-pi4b'"
    #  ],
    #  "image": "bash",
    #  "name": "Push pi4b to Attic"
    #}
    #{
    #  "commands": [
    #    "nix build '.#nixosConfigurations.pi5.config.system.build.toplevel' -o 'result-pi5'"
    #  ],
    #  "image": "bash",
    #  "name": "Build pi5"
    #},
    #{
    #  "commands": [
    #    "attic push lounge-rocks:nix-cache 'result-pi5'"
    #  ],
    #  "image": "bash",
    #  "name": "Push pi5 to Attic"
    #}
  ]
}
